#! /bin/bash

#lock your terminal

#prevent user to interrupt this script (to defeat the lock) 
trap '' 1 2 3 18
#prevent displaying characters typed at the keyboard
stty -echo
echo -n "key: "
read key_1
echo
echo -n "Again: "
read key_2
echo 
key_3=
if [ "$key_1" = "$key_2" ]
  then
    #clear the screen (lock it ...)
    tput clear
    until [ "$key_3" = "$key_2" ]
    do 
      read key_3
    done
  else
    echo "lockIt: keys do not match" 1>&2
fi
stty echo

